server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/ # Eureka 单机版
      #defaultZone:  http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ # Eureka集群版本