server:
  port: 8001
spring:
  application:
    # 见 pom.xml 文件中的 <name>consumer-user</name>
    name: provider-ticket

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
