# 服务端口号
server:
  port: 8002

# 服务名称
spring:
  application:
    name: cloud-payment-service
  #  zipkin:
  #    # 放到 zipkin上
  #    base-url: http://localhost:9411
  #  sleuth:
  #    sampler:
  #      # 采样率介于0-1之间，1表示全部采集
  #      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源类型
    #driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_payment?useUnicode=true&characterEncoding=utf-8
    username: root
    password: GJXAIOU

    # 和 MyBatis 的整合

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gjxaiou.springcloud.entities  #实体类所在包


eureka:
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/ # Eureka 单机版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ # Eureka集群版本

  instance:
    # 主机名称：服务名称的修改
    instance-id: payment8002
    # 暴露显示 IP 地址
    prefer-ip-address: true
##    #eureka客户端发送心跳的时间间隔，默认30s
##    lease-renewal-interval-in-seconds: 1
##    #eureka服务端在收到最后一次心跳等待的时间上线，默认90s
##    lease-expiration-duration-in-seconds: 2