server:
  port: 9527

spring:
  application:
    # 设定服务名称
    name: cloud-gateway
  # 路由规则映射
  cloud:
    gateway:
      # 开启从服务在注册中心动态创建路由的功能
      discovery:
        locator:
          enabled: true
      routes: # 可以配置多个路由
        - id: payment_routh1   # 路由的 ID，没有固定规则但是要求唯一，建议配合服务名称
          # uri: http://localhost:8001  # 匹配后提供服务的路由地址
          # 使用服务名称代替具体的服务， lb 表示负载均衡
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   # 断言：路径相匹配的进行路由

        - id: payment_routh2
          # uri: http://localhost:8001
          # 使用服务名称代替具体的服务， lb 表示负载均衡
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
    # 服务提供者 provider 注册进 Eureka 服务列表中，网关本身也是一个微服务
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


